
services:
  mysql:
    image: mysql:latest
    container_name: xpe-mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xpe
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - xpe-network

  adminer:
    image: adminer
    container_name: xpe-adminer
    ports:
      - "8888:8080"
    networks:
      - xpe-network

# crie a rede bridge
networks:
  xpe-network:

# crie o volume
volumes:
  mysql-data: